# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe2891ab7b98f9775f46fa1fd90910ce0db24ae2ee692ac37011cbb9273cbac6debeba462dfe507bd19f82b634df83922fce927757bcf09ee77598609825944b

test:
  secret_key_base: f6595ee7f5cffb1693116fc9ae094f510511e85b3e9382bf3d122657b5f6f34ff1472d5b2200b27a161706567dd29e6742cedd82b60ea532b18476a3b9f556cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
